# Generated by Django 5.0.6 on 2024-05-30 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TODO', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(max_length=6),
        ),
    ]
